GENDER_MALE = 'M'
GENDER_FEMALE = 'F'
GENDER_CHOICES = (
    (GENDER_MALE, 'Male'),
    (GENDER_FEMALE, 'Female'),
)

CITY_ALMATY = 'ALA'
CITY_ASTANA = 'AST'
CITIES = (
    (CITY_ALMATY, 'Almaty'),
    (CITY_ASTANA, 'Astana'),
)
